// Generated by `UPDATE_OPTION_KEYS=1 cargo test -p vista_wasm --test option_keys`
// from the option types in `crates/vista_types`; do not edit by hand.
//
// The keys the engine reads, for the wrapper's unknown-key warnings: an
// object of keys, `0` for any value, `[shape]` for a list of objects.
// `engine` holds every setter's options under their names.

import type { OptionKeys } from "./errors.js";

export const OPTION_KEYS = {
  engine: {
    render: {
      width: 0,
      height: 0,
      devicePixelRatio: 0
    },
    camera: {
      position: 0,
      target: 0,
      rollDegrees: 0,
      fieldOfViewDegrees: 0,
      nearMetres: 0,
      farMetres: 0,
      minimumHeightAboveTerrainMetres: 0,
      allowUnderground: 0
    },
    sun: {
      azimuthDegrees: 0,
      elevationDegrees: 0,
      intensity: 0
    },
    atmosphere: {
      rayleighStrength: 0,
      mieStrength: 0,
      hazeDistanceMetres: 0,
      exposure: 0,
      skyTint: 0
    },
    water: {
      enabled: 0,
      seaLevelMetres: 0,
      waveScale: 0,
      reflectivity: 0,
      shorelineSoftnessMetres: 0,
      waves: {
        enabled: 0,
        amplitudeMetres: 0,
        wavelengthMetres: 0,
        directionDegrees: 0,
        steepness: 0,
        speed: 0,
        directionalSpread: 0
      },
      rivers: {
        enabled: 0,
        minCatchmentKm2: 0,
        widthScale: 0,
        currentSpeed: 0,
        snowmelt: 0,
        springs: 0,
        meanders: 0,
        meanderMaturity: 0,
        braiding: 0,
        waterfalls: 0,
        inflow: [{
          position: 0,
          dischargeCubicMetresPerSecond: 0
        }],
        riparian: 0
      },
      currentDirectionDegrees: 0,
      currentSpeed: 0,
      shallowColour: 0,
      deepColour: 0,
      clarityMetres: 0,
      foam: 0,
      reflections: 0,
      eddies: 0,
      refraction: 0
    },
    flora: {
      enabled: 0,
      density: 0,
      treeLineMetres: 0,
      seedOffset: 0,
      maxInstances: 0,
      treeQuality: 0,
      speciesVariation: 0,
      windStrength: 0,
      meshDistanceMetres: 0,
      speciesRules: [{
        biome: 0,
        species: [{
          species: 0,
          weight: 0
        }],
        density: 0
      }],
      variantsPerSpecies: 0
    },
    grass: {
      enabled: 0,
      style: 0,
      density: 0,
      viewDistanceMetres: 0,
      seedOffset: 0,
      maxInstances: 0,
      forestFloor: 0
    },
    clouds: {
      style: 0,
      coverage: 0,
      speed: 0,
      heightMetres: 0,
      colour: 0,
      seedOffset: 0,
      raymarchSteps: 0,
      windDirectionDegrees: 0,
      evolution: 0,
      thicknessMetres: 0,
      density: 0,
      castShadows: 0,
      resolutionScale: 0,
      cirrus: 0,
      cirrusHeightMetres: 0,
      cirrusSpeed: 0,
      temporal: 0,
      stratiform: 0,
      towering: 0,
      baseDarkness: 0,
      raggedBase: 0,
      rainShafts: 0,
      baseVariation: 0,
      baseLumpiness: 0,
      altocumulus: 0,
      altostratus: 0,
      altoHeightMetres: 0,
      altoSpeed: 0
    },
    mist: {
      style: 0,
      density: 0,
      baseHeightMetres: 0,
      heightFalloffMetres: 0,
      colour: 0,
      riseAboveWater: 0,
      seedOffset: 0,
      windDirectionDegrees: 0,
      windSpeedMetresPerSecond: 0,
      sunScattering: 0
    },
    quality: {
      preset: 0,
      maxClipmapLevels: 0,
      floraDensityScale: 0,
      renderDistanceMetres: 0,
      renderFadeMetres: 0,
      detailDistanceMetres: 0,
      cloudDistanceMetres: 0,
      cloudFadeMetres: 0,
      maxFrameRate: 0,
      renderScale: 0,
      dynamicResolution: 0,
      minRenderScale: 0,
      vegetationDetailMetres: 0,
      canopyDistanceMetres: 0,
      maxTreeInstances: 0,
      maxGrassInstances: 0,
      maxTreeTriangles: 0,
      grassDetailMetres: 0,
      splitTreeTiming: 0
    },
    biomes: {
      enabled: 0,
      seedOffset: 0,
      temperatureBias: 0,
      moistureBias: 0,
      climateScaleMetres: 0,
      volcanism: 0,
      beachHeightMetres: 0,
      snowLineMetres: 0,
      meanTemperatureCelsius: 0
    },
    weather: {
      enabled: 0,
      state: 0,
      autoCycle: 0,
      stateDurationSeconds: 0,
      transitionSeconds: 0,
      allowSnow: 0,
      seedOffset: 0,
      windDirectionDegrees: 0,
      windScale: 0,
      precipitationScale: 0,
      lensDrops: 0,
      lensDropCount: 0,
      lensDropMinSize: 0,
      lensDropMaxSize: 0,
      effects: {
        clouds: 0,
        mist: 0,
        wind: 0,
        water: 0,
        precipitation: 0,
        ground: 0,
        lightning: 0
      },
      presets: 0,
      regional: 0,
      regionSizeKm: 0
    },
    shadows: {
      terrain: {
        enabled: 0,
        strength: 0,
        softness: 0
      },
      trees: {
        enabled: 0,
        distanceMetres: 0,
        resolution: 0,
        strength: 0,
        softness: 0
      },
      clouds: {
        enabled: 0,
        strength: 0
      }
    },
    surface: {
      textures: 0,
      detailNormals: 0,
      textureScale: 0,
      materialTints: 0,
      rockiness: 0,
      boulders: 0,
      boulderDistanceMetres: 0
    }
  },
  terrain: {
    seed: 0,
    size: 0,
    horizontalScaleMetres: 0,
    verticalScale: 0,
    baseHeightMetres: 0,
    seaLevelMetres: 0,
    noise: {
      kind: 0,
      octaves: 0,
      gain: 0,
      lacunarity: 0,
      warp: 0
    },
    shape: {
      island: 0,
      terrace: 0,
      basin: 0,
      canyon: 0,
      crater: 0
    },
    erosion: {
      hydraulicIterations: 0,
      thermalIterations: 0,
      rainAmount: 0,
      evaporation: 0,
      sedimentCapacity: 0,
      talusAngleDegrees: 0,
      quality: 0
    },
    landform: 0,
    edges: 0
  },
  raw: {
    width: 0,
    height: 0,
    sampleFormat: 0,
    byteOrder: 0,
    metresPerSample: 0,
    heightScaleMetres: 0,
    noDataValue: 0,
    seaLevelMetres: 0,
    landform: 0
  },
  dem: {
    verticalScale: 0,
    generateNormals: 0,
    generateMaterialMasks: 0
  }
} satisfies OptionKeys;
